//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLyMVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuXuatHang
    {
        public int IdSanPham { get; set; }
        public int IdPhieuXuatHang { get; set; }
        public int SoLuong { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual PhieuXuatHang PhieuXuatHang { get; set; }
    }
}
