//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLyMVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietBaoCao
    {
        public int IdDaiLy { get; set; }
        public int IdBangBaoCao { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual BangBaoCao BangBaoCao { get; set; }
        public virtual DaiLy DaiLy { get; set; }
    }
}
