//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLyMVVM.Model
{
    using QuanLyDaiLyMVVM.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class LoaiDaiLy : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiDaiLy()
        {
            this.DaiLies = new HashSet<DaiLy>();
        }

        private int _Id;
        public int Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }
        private string _Ten;
        public string Ten { get => _Ten; set { _Ten = value; OnPropertyChanged(); } }
        private decimal _SoTienNoToiDa;
        public decimal SoTienNoToiDa { get => _SoTienNoToiDa; set { _SoTienNoToiDa = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        private ICollection<DaiLy> _DaiLies;
        public virtual ICollection<DaiLy> DaiLies { get => _DaiLies; set { _DaiLies = value; OnPropertyChanged(); } }
    }
}
