//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLyMVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int Id { get; set; }
        public string Ten { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public Nullable<int> VaiTro { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
