//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLyMVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyDinh
    {
        public int Id { get; set; }
        public string TenQuyDinh { get; set; }
        public int GiaTri { get; set; }
        public string KieuDuLieu { get; set; }
        public bool TrangThai { get; set; }
    }
}
