//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLyMVVM.Model
{
    using QuanLyDaiLyMVVM.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan: BaseViewModel
    {
        private int _Id;
        public int Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }
        private string _TenDangNhap;
        public string TenDangNhap { get => _TenDangNhap; set { _TenDangNhap = value; OnPropertyChanged(); } }
        private string _MatKhau;
        public string MatKhau { get => _MatKhau; set { _MatKhau = value; OnPropertyChanged(); } }

        private NhanVien _NhanVien;
        public virtual NhanVien NhanVien { get=>_NhanVien; set { _NhanVien = value; OnPropertyChanged(); } }
    }
}
