CREATE TABLE [DaiLy] (
	ID integer NOT NULL,
	Ten string NOT NULL,
	DienThoai string NOT NULL,
	DiaChi string NOT NULL,
	NgayTiepNhan date NOT NULL,
	Quan string NOT NULL,
	Email string NOT NULL,
	LoaiDaiLy integer NOT NULL,
	IsRemove boolean NOT NULL,
  CONSTRAINT [PK_DAILY] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [LoaiDaiLy] (
	MaLoai integer NOT NULL,
	SoTienNoToiDa decimal NOT NULL,
  CONSTRAINT [PK_LOAIDAILY] PRIMARY KEY CLUSTERED
  (
  [MaLoai] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [QuyDinh] (
	MaQuyDinh integer NOT NULL,
	TenQuyDinh string NOT NULL,
	GiaTri integer NOT NULL,
	KieuDuLieu string NOT NULL,
	TrangThai boolean NOT NULL,
  CONSTRAINT [PK_QUYDINH] PRIMARY KEY CLUSTERED
  (
  [MaQuyDinh] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [BangBaoCaoThang] (
	ID integer NOT NULL,
	Thang integer NOT NULL,
  CONSTRAINT [PK_BANGBAOCAOTHANG] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [BaoCaoDoanhSo] (
	ID integer NOT NULL,
	SoPhieuXuat integer NOT NULL,
	TongTriGia decimal NOT NULL,
	TyLe float NOT NULL,
  CONSTRAINT [PK_BAOCAODOANHSO] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [BaoCaoCongNo] (
	ID integer NOT NULL,
	NoDau decimal NOT NULL,
	PhatSinh decimal NOT NULL,
  CONSTRAINT [PK_BAOCAOCONGNO] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [ChiTietBaoCao] (
	IDDaiLy integer NOT NULL,
	IDBaoCao integer NOT NULL,
	NgayTao date NOT NULL,
  CONSTRAINT [PK_CHITIETBAOCAO] PRIMARY KEY CLUSTERED
  (
  [IDDaiLy] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [PhieuDaiLy] (
	ID integer NOT NULL,
	NgayLapPhieu date NOT NULL,
	IDDaiLy integer NOT NULL,
  CONSTRAINT [PK_PHIEUDAILY] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [PhieuThuTien] (
	ID integer NOT NULL,
	SoTienThu decimal NOT NULL,
  CONSTRAINT [PK_PHIEUTHUTIEN] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [PhieuXuatHang] (
	ID integer NOT NULL,
	DonViTinh string NOT NULL,
	TongTien decimal NOT NULL,
  CONSTRAINT [PK_PHIEUXUATHANG] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [LoaiSanPham] (
	ID integer NOT NULL,
	Ten string NOT NULL,
  CONSTRAINT [PK_LOAISANPHAM] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [SanPham] (
	ID integer NOT NULL,
	Ten string NOT NULL,
	DonGia decimal NOT NULL,
	SoLuong integer NOT NULL,
	IDLoaiSanPham integer NOT NULL,
	IDNguonNhap integer NOT NULL,
  CONSTRAINT [PK_SANPHAM] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [NguonNhap] (
	ID integer NOT NULL,
	Ten string NOT NULL,
	DiaChi string NOT NULL,
	SoDienThoai string NOT NULL,
  CONSTRAINT [PK_NGUONNHAP] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [ChiTietPhieuXuatHang] (
	IDSanPham integer NOT NULL,
	IDPhieuXuatHang integer NOT NULL,
	SoLuong integer NOT NULL,
	GiaBan decimal NOT NULL,
  CONSTRAINT [PK_CHITIETPHIEUXUATHANG] PRIMARY KEY CLUSTERED
  (
  [IDSanPham] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
ALTER TABLE [DaiLy] WITH CHECK ADD CONSTRAINT [DaiLy_fk0] FOREIGN KEY ([LoaiDaiLy]) REFERENCES [LoaiDaiLy]([MaLoai])
ON UPDATE CASCADE
GO
ALTER TABLE [DaiLy] CHECK CONSTRAINT [DaiLy_fk0]
GO




ALTER TABLE [BaoCaoDoanhSo] WITH CHECK ADD CONSTRAINT [BaoCaoDoanhSo_fk0] FOREIGN KEY ([ID]) REFERENCES [BangBaoCaoThang]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [BaoCaoDoanhSo] CHECK CONSTRAINT [BaoCaoDoanhSo_fk0]
GO

ALTER TABLE [BaoCaoCongNo] WITH CHECK ADD CONSTRAINT [BaoCaoCongNo_fk0] FOREIGN KEY ([ID]) REFERENCES [BangBaoCaoThang]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [BaoCaoCongNo] CHECK CONSTRAINT [BaoCaoCongNo_fk0]
GO

ALTER TABLE [ChiTietBaoCao] WITH CHECK ADD CONSTRAINT [ChiTietBaoCao_fk0] FOREIGN KEY ([IDDaiLy]) REFERENCES [DaiLy]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [ChiTietBaoCao] CHECK CONSTRAINT [ChiTietBaoCao_fk0]
GO
ALTER TABLE [ChiTietBaoCao] WITH CHECK ADD CONSTRAINT [ChiTietBaoCao_fk1] FOREIGN KEY ([IDBaoCao]) REFERENCES [BangBaoCaoThang]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [ChiTietBaoCao] CHECK CONSTRAINT [ChiTietBaoCao_fk1]
GO

ALTER TABLE [PhieuDaiLy] WITH CHECK ADD CONSTRAINT [PhieuDaiLy_fk0] FOREIGN KEY ([IDDaiLy]) REFERENCES [DaiLy]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [PhieuDaiLy] CHECK CONSTRAINT [PhieuDaiLy_fk0]
GO

ALTER TABLE [PhieuThuTien] WITH CHECK ADD CONSTRAINT [PhieuThuTien_fk0] FOREIGN KEY ([ID]) REFERENCES [PhieuDaiLy]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [PhieuThuTien] CHECK CONSTRAINT [PhieuThuTien_fk0]
GO

ALTER TABLE [PhieuXuatHang] WITH CHECK ADD CONSTRAINT [PhieuXuatHang_fk0] FOREIGN KEY ([ID]) REFERENCES [PhieuDaiLy]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [PhieuXuatHang] CHECK CONSTRAINT [PhieuXuatHang_fk0]
GO


ALTER TABLE [SanPham] WITH CHECK ADD CONSTRAINT [SanPham_fk0] FOREIGN KEY ([IDLoaiSanPham]) REFERENCES [LoaiSanPham]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [SanPham] CHECK CONSTRAINT [SanPham_fk0]
GO
ALTER TABLE [SanPham] WITH CHECK ADD CONSTRAINT [SanPham_fk1] FOREIGN KEY ([IDNguonNhap]) REFERENCES [NguonNhap]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [SanPham] CHECK CONSTRAINT [SanPham_fk1]
GO


ALTER TABLE [ChiTietPhieuXuatHang] WITH CHECK ADD CONSTRAINT [ChiTietPhieuXuatHang_fk0] FOREIGN KEY ([IDSanPham]) REFERENCES [SanPham]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [ChiTietPhieuXuatHang] CHECK CONSTRAINT [ChiTietPhieuXuatHang_fk0]
GO
ALTER TABLE [ChiTietPhieuXuatHang] WITH CHECK ADD CONSTRAINT [ChiTietPhieuXuatHang_fk1] FOREIGN KEY ([IDPhieuXuatHang]) REFERENCES [PhieuXuatHang]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [ChiTietPhieuXuatHang] CHECK CONSTRAINT [ChiTietPhieuXuatHang_fk1]
GO

