//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangBaoCaoThang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BangBaoCaoThang()
        {
            this.ChiTietBaoCaos = new HashSet<ChiTietBaoCao>();
        }
    
        public int ID { get; set; }
        public int Thang { get; set; }
        public Nullable<int> Nam { get; set; }
    
        public virtual BaoCaoCongNo BaoCaoCongNo { get; set; }
        public virtual BaoCaoDoanhSo BaoCaoDoanhSo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietBaoCao> ChiTietBaoCaos { get; set; }
    }
}
