//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDaiLy
    {
        public int ID { get; set; }
        public System.DateTime NgayLapPhieu { get; set; }
        public int IDDaiLy { get; set; }
    
        public virtual DaiLy DaiLy { get; set; }
        public virtual PhieuThuTien PhieuThuTien { get; set; }
        public virtual PhieuXuatHang PhieuXuatHang { get; set; }
    }
}
