//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLyMVVM.Model
{
    using QuanLyDaiLyMVVM.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class ChiTietPhieuXuatHang : BaseViewModel
    {
        private int _IdSanPham;
        public int IdSanPham { get => _IdSanPham; set { _IdSanPham = value; OnPropertyChanged(); } }

        private int _IdPhieuXuatHang;
        public int IdPhieuXuatHang { get => _IdPhieuXuatHang; set { _IdPhieuXuatHang = value; OnPropertyChanged(); } }

        private int _SoLuong;
        public int SoLuong { get => _SoLuong; set { _SoLuong = value; OnPropertyChanged(); } }

        private decimal _GiaBan;
        public decimal GiaBan { get => _GiaBan; set { _GiaBan = value; OnPropertyChanged(); } }

        private SanPham _SanPham;
        public virtual SanPham SanPham { get => _SanPham; set { _SanPham = value; OnPropertyChanged(); } }

        private PhieuXuatHang _PhieuXuatHang;
        public virtual PhieuXuatHang PhieuXuatHang { get => _PhieuXuatHang; set { _PhieuXuatHang = value; OnPropertyChanged(); } }
    }
}