//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDaiLyMVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaiLy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DaiLy()
        {
            this.PhieuDaiLies = new HashSet<PhieuDaiLy>();
        }
    
        public int Id { get; set; }
        public string Ten { get; set; }
        public string DienThoai { get; set; }
        public string DiaChi { get; set; }
        public System.DateTime NgayTiepNhan { get; set; }
        public string Quan { get; set; }
        public string Email { get; set; }
        public int IdLoaiDaiLy { get; set; }
        public bool IsRemove { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual LoaiDaiLy LoaiDaiLy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDaiLy> PhieuDaiLies { get; set; }
    }
}
